# Generated by Django 5.0.7 on 2024-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
