# Generated by Django 5.0.7 on 2024-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_products', '0002_cart_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
