# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# получение категорий
GET {{baseUrl}}/categories/
Content-Type: application/json
###

# получение категории
GET {{baseUrl}}/categories/1/
Content-Type: application/json

###

# получение продуктов
GET {{baseUrl}}/goods/
Content-Type: application/json

###

# создание записи в карзине покупок
POST {{baseUrl}}/basketgood/
Content-Type: application/json
Authorization: Token b1d0106ea4208fedd2c67c81436904176142e287
//Authorization: Token 6459fe7fc484888bd55a56633229e7885dc97c53

{
  "good": 3,
  "quantity": 10
}

###

# попытка поменять количенство
PATCH {{baseUrl}}/basketgood/2/
Content-Type: application/json
Authorization: Token b1d0106ea4208fedd2c67c81436904176142e287

{
  "quantity": 15
}

###

# получение данных карзины
GET {{baseUrl}}/basket/2/
Content-Type: application/json
//Authorization: Token 6459fe7fc484888bd55a56633229e7885dc97c53
Authorization: Token b1d0106ea4208fedd2c67c81436904176142e287

###

# удаление продукта
DELETE {{baseUrl}}/basketgood/1/
Content-Type: application/json
Authorization: Token 6459fe7fc484888bd55a56633229e7885dc97c53

###

# очистить карзину
DELETE {{baseUrl}}/basket/0/
Content-Type: application/json
Authorization: Token b1d0106ea4208fedd2c67c81436904176142e287
