# Generated by Django 5.0.7 on 2024-08-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_alter_basketgood_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketgood',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baskets.basket'),
        ),
    ]
