# Generated by Django 5.0.7 on 2024-08-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_alter_basketgood_basket'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='goods',
            field=models.ManyToManyField(through='baskets.BasketGood', to='goods.good'),
        ),
        migrations.AlterField(
            model_name='basketgood',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baskets.basket'),
        ),
    ]
