# Generated by Django 5.0.7 on 2024-08-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_basket_goods_alter_basketgood_basket'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='goods',
        ),
        migrations.AlterField(
            model_name='basketgood',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='baskets.basket'),
        ),
        migrations.AlterField(
            model_name='basketgood',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.good'),
        ),
    ]
