# Generated by Django 5.0.7 on 2024-08-02 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='Изображение')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods', verbose_name='Товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.size', verbose_name='Размер картинки')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_price', models.DateTimeField(auto_created=True, verbose_name='Дата цены')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='goods.goods', verbose_name='Товар')),
            ],
            options={
                'indexes': [models.Index(fields=['date_price'], name='goods_price_date_pr_a6eaf3_idx')],
            },
        ),
    ]
