# Generated by Django 5.0.7 on 2024-08-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_category_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name_size',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='images',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_name', to='goods.size'),
        ),
    ]
