# Generated by Django 5.0.7 on 2024-08-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_goods_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.category'),
        ),
    ]
